# Generated by Django 4.0 on 2022-01-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('eemail', models.CharField(max_length=200)),
                ('econtact', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
